name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, from push!
        
  build-on-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Run a one-line script
        run: echo Hello, from tag!
